# Generated by Django 3.0 on 2021-10-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_company', models.CharField(max_length=100)),
                ('comp_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('comp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comp_name', models.CharField(blank=True, max_length=40, null=True)),
                ('comp_address', models.CharField(blank=True, max_length=600, null=True)),
                ('comp_state', models.CharField(blank=True, max_length=400, null=True)),
                ('comp_website', models.CharField(blank=True, max_length=400, null=True)),
                ('comp_gstin', models.CharField(blank=True, max_length=400, null=True)),
                ('comp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_ad', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cst_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ladgernamedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledeger_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('ledeger_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ledeger_name', models.CharField(blank=True, max_length=40, null=True)),
                ('ledeger_address', models.CharField(blank=True, max_length=600, null=True)),
                ('ledeger_state', models.CharField(blank=True, max_length=400, null=True)),
                ('ledeger_website', models.CharField(blank=True, max_length=400, null=True)),
                ('ledeger_gstin', models.CharField(blank=True, max_length=400, null=True)),
                ('created_by', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
