# Generated by Django 3.0 on 2021-10-19 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalbankname', models.CharField(blank=True, max_length=40, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EpaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='raw')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('s_date', models.DateField(blank=True, null=True)),
                ('e_date', models.DateField(blank=True, null=True)),
                ('entry', models.IntegerField(blank=True, null=True)),
                ('bankname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_payment.BankDetails')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legdername', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='masterBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mstbnk_nm', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Transaction', models.TextField(blank=True, null=True)),
                ('Legder', models.CharField(blank=True, max_length=200, null=True)),
                ('Ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('AccountantNarration', models.CharField(blank=True, max_length=500, null=True)),
                ('Credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('EditLegder', models.CharField(blank=True, max_length=200, null=True)),
                ('EditLegder2', models.CharField(blank=True, max_length=200, null=True)),
                ('EditLegderamount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('EditLegder2amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ListLegder1', models.CharField(blank=True, max_length=200, null=True)),
                ('ListAmount1', models.CharField(blank=True, max_length=200, null=True)),
                ('ListLegder2', models.CharField(blank=True, max_length=200, null=True)),
                ('ListAmount2', models.CharField(blank=True, max_length=200, null=True)),
                ('Vouchetype', models.CharField(blank=True, choices=[('PURCHASE VOUCHER', 'PURCHASE VOUCHER'), ('SALES VOUCHER', 'SALES VOUCHER'), ('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER'), ('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('PAYMENT VOUCHER', 'PAYMENT VOUCHER'), ('CONTRA VOUCHER', 'CONTRA VOUCHER'), ('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER')], max_length=100, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='e_payment.EpaymentDetails')),
            ],
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bankname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_payment.masterBank'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='comp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companydata'),
        ),
    ]
