# Generated by Django 3.2.5 on 2021-11-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='finalbankname',
        ),
        migrations.AddField(
            model_name='showdata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='showdata',
            name='prevoius_created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showdata',
            name='prevoius_zero_cr_dr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='epaymentdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ledgerdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='masterbank',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='Vouchetype',
            field=models.CharField(blank=True, choices=[('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER'), ('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('SALES VOUCHER', 'SALES VOUCHER'), ('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER'), ('PAYMENT VOUCHER', 'PAYMENT VOUCHER'), ('CONTRA VOUCHER', 'CONTRA VOUCHER'), ('PURCHASE VOUCHER', 'PURCHASE VOUCHER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='showdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
