# Generated by Django 3.1.4 on 2021-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherinvoiceentry',
            name='Vouchetype',
            field=models.CharField(blank=True, choices=[('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER'), ('PURCHASE VOUCHER', 'PURCHASE VOUCHER'), ('SALES VOUCHER', 'SALES VOUCHER'), ('PAYMENT VOUCHER', 'PAYMENT VOUCHER'), ('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER'), ('CONTRA VOUCHER', 'CONTRA VOUCHER')], max_length=100, null=True),
        ),
    ]
