# Generated by Django 3.0 on 2021-12-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvtabledata',
            name='GST_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voucherinvoiceentry',
            name='Vouchetype',
            field=models.CharField(blank=True, choices=[('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER'), ('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('CONTRA VOUCHER', 'CONTRA VOUCHER'), ('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('SALES VOUCHER', 'SALES VOUCHER'), ('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER'), ('PAYMENT VOUCHER', 'PAYMENT VOUCHER'), ('PURCHASE VOUCHER', 'PURCHASE VOUCHER')], max_length=100, null=True),
        ),
    ]
