# Generated by Django 3.0 on 2021-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20211202_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvtabledata',
            name='quantity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voucherinvoiceentry',
            name='Vouchetype',
            field=models.CharField(blank=True, choices=[('PAYMENT VOUCHER', 'PAYMENT VOUCHER'), ('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER'), ('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('SALES VOUCHER', 'SALES VOUCHER'), ('CONTRA VOUCHER', 'CONTRA VOUCHER'), ('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER'), ('PURCHASE VOUCHER', 'PURCHASE VOUCHER')], max_length=100, null=True),
        ),
    ]
