# Generated by Django 3.1.4 on 2021-10-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20211012_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='GSTTotal',
            field=models.FloatField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='voucherinvoiceentry',
            name='Vouchetype',
            field=models.CharField(blank=True, choices=[('PURCHASE VOUCHER', 'PURCHASE VOUCHER'), ('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('PAYMENT VOUCHER', 'PAYMENT VOUCHER'), ('SALES VOUCHER', 'SALES VOUCHER'), ('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER'), ('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('CONTRA VOUCHER', 'CONTRA VOUCHER'), ('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER')], max_length=100, null=True),
        ),
    ]
