# Generated by Django 3.1.4 on 2021-10-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20211013_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherinvoiceentry',
            name='Vouchetype',
            field=models.CharField(blank=True, choices=[('CONTRA VOUCHER', 'CONTRA VOUCHER'), ('PURCHASE VOUCHER', 'PURCHASE VOUCHER'), ('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER'), ('PAYMENT VOUCHER', 'PAYMENT VOUCHER'), ('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER'), ('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('SALES VOUCHER', 'SALES VOUCHER')], max_length=100, null=True),
        ),
    ]
