# Generated by Django 3.1.4 on 2021-10-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20211013_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherinvoiceentry',
            name='Vouchetype',
            field=models.CharField(blank=True, choices=[('SALES VOUCHER', 'SALES VOUCHER'), ('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('CONTRA VOUCHER', 'CONTRA VOUCHER'), ('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('PURCHASE VOUCHER', 'PURCHASE VOUCHER'), ('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER'), ('PAYMENT VOUCHER', 'PAYMENT VOUCHER'), ('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voucherinvoiceentry',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
