# Generated by Django 3.0 on 2021-10-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20211013_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherinvoiceentry',
            name='Vouchetype',
            field=models.CharField(blank=True, choices=[('PURCHASE VOUCHER', 'PURCHASE VOUCHER'), ('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER'), ('CONTRA VOUCHER', 'CONTRA VOUCHER'), ('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('SALES VOUCHER', 'SALES VOUCHER'), ('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER'), ('PAYMENT VOUCHER', 'PAYMENT VOUCHER')], max_length=100, null=True),
        ),
    ]
