# Generated by Django 3.0 on 2021-10-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20211014_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherinvoiceentry',
            name='Vouchetype',
            field=models.CharField(blank=True, choices=[('JOURNAL VOUCHER', 'JOURNAL VOUCHER'), ('CONTRA VOUCHER', 'CONTRA VOUCHER'), ('SALES VOUCHER', 'SALES VOUCHER'), ('RECEIPT VOUCHER', 'RECEIPT VOUCHER'), ('DEBIT NOTE VOUCHER', 'DEBIT NOTE VOUCHER'), ('CREDIT NOTE VOUCHER', 'CREDIT NOTE VOUCHER'), ('PURCHASE VOUCHER', 'PURCHASE VOUCHER'), ('PAYMENT VOUCHER', 'PAYMENT VOUCHER')], max_length=100, null=True),
        ),
    ]
